<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>c8a30c4b-227a-48f3-945b-ce83c8425e90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='QuickLinks']/a[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(3) > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#QuickLinks >> internal:role=link >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f5fd4bc1-67ec-43bd-b36c-8f2a89f1a600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/sm_reptiles.gif</value>
      <webElementGuid>51c03676-4197-4329-9f38-3e620b834467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QuickLinks&quot;)/a[3]/img[1]</value>
      <webElementGuid>de8e714e-419d-49c3-8a8f-269c219a192d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='QuickLinks']/a[3]/img</value>
      <webElementGuid>0000e1a7-35cc-4eb1-9214-70ba7550d77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>cf591a81-cb39-4857-80cf-f39492f69d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/sm_reptiles.gif']</value>
      <webElementGuid>25fd27e8-3c56-436a-93f7-819f0f4641fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
