<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accepted usernames are                s_40dcc1</name>
   <tag></tag>
   <elementGuidId>3df8e9eb-d135-48d0-b6fc-32d796b8c168</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login_credentials']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login_credentials</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Accepted usernames are: standard_user locked_out_user problem_user performance_g&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ea73aea-7b30-4358-bee9-e8ef32606a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>c6e951b3-e611-43bf-aacd-2b5ae48088f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>1872e8eb-280d-414d-adc9-b0e2298a4972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Accepted usernames are:
                standard_user
                locked_out_user
                problem_user
                performance_glitch_user

            </value>
      <webElementGuid>d18548ff-92d7-4958-a2ba-ddb22d3d7181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_credentials&quot;)</value>
      <webElementGuid>5846ae50-2ca7-4765-a1e8-278a3ebd514c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='login_credentials']</value>
      <webElementGuid>6466e7d8-51a3-41fa-a236-87b9dc75fa28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='standard_user']/parent::*</value>
      <webElementGuid>c6e6c763-19c6-4d46-8997-b0db115dae88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>6992342e-b1fa-48f6-936c-5fdb5ef69fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'login_credentials' and (text() = '
                Accepted usernames are:
                standard_user
                locked_out_user
                problem_user
                performance_glitch_user

            ' or . = '
                Accepted usernames are:
                standard_user
                locked_out_user
                problem_user
                performance_glitch_user

            ')]</value>
      <webElementGuid>15e60e12-095e-4770-a090-3642e083bd4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
